### ISSUE TITLE
🙏

### ISSUE THREAD

**Issue by kotinash** [shadowwwmain/Yern-Leak-V2#1]
please dont global ban my burner account 🙏i spent whole 3 minutes making it

![image](https://github.com/shadowwwmain/Yern-Leak-V2/assets/92477814/5e6d251d-2db1-4ec6-a4f8-b22b76cdcdfa)

**Comment by imWildy** [comment]
oh no ggslash antip2w account is getting fairplay global banned!!!!

**Comment by kotinash** [comment]
> oh no ggslash antip2w account is getting fairplay global banned!!!!

😭
